import * as dotenv from 'dotenv';

const envFileMap: Record<string, string> = {
  production: '.env.production',
  development: '.env.development',
};

const nodeEnv = process.env['NODE_ENV'] ?? 'development';
const envFile = envFileMap[nodeEnv] ?? '.env.development';

dotenv.config({ path: envFile });

import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'tsx prisma/seed.ts',
  },
  datasource: {
    url: env('DATABASE_URL'),
  },
});

// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// import 'dotenv/config';
// import { defineConfig } from 'prisma/config';

// export default defineConfig({
//   schema: 'prisma/schema.prisma',
//   migrations: {
//     path: 'prisma/migrations',
//   },
//   datasource: {
//     url: process.env['DATABASE_URL'],
//   },
// });
